#
# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT
#

# dongle acts as the split central; halves are converted to peripherals via
# -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n on their build.yaml entries
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# BLE
CONFIG_BT_BAS=n
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n

# usb-name
CONFIG_USB_DEVICE_MANUFACTURER="Eyelash Peripherals"

CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n
